---
- name: Execute show version and show lldp neighbors through nxos_command
  hosts: nxos
  gather_facts: False
  
  tasks:
  - name: Run show version command and register variable
    nxos_command:
      commands:
        - show version
        - show lldp neighbors
    register: output

  - name: Debug registered variable result
    debug:
      msg: "{{ output.stdout_lines[1] }}"
