---
- name: Parse via Genie - show version
  hosts: nxos
  gather_facts: False
  collections:
    - clay584.genie
  vars:
    command: "show version"

  tasks:
  - name: Grab show version output
    nxos_command:
      commands:
        - "{{ command }}"
    register: output

  - set_fact:
      genie_parse: "{{ output.stdout.0 | clay584.genie.parse_genie(command=command, os=ansible_network_os) }}"

  - debug:
      msg: "The NXOS firmware version is: {{ genie_parse['platform']['software']['system_version'] }}"
