---
- name: Configure DDI Settings using import_tasks and conditionals
  hosts: cisco
  gather_facts: True

  tasks:
  #- debug:
  #    var: ansible_facts.net_iostype
   
  - name: Configure dns / domain-name / ntp for IOS hosts
    import_tasks: ios.yml
    when: ansible_facts.net_iostype == "IOS"

  - name: Configure dns / domain-name / ntp for IOS-XE hosts
    import_tasks: iosxe.yml
    when: ansible_facts.net_iostype == "IOS-XE"
