---
- name: Issue LLDP Neighbors and find for regex
  hosts: nxos
  gather_facts: False

  tasks:
  - name: Issue a show lldp neighbors command and register output
    nxos_command:
      commands:
        - show lldp neighbors
    register: output

  - set_fact:
      output: "{{ output.stdout.0 }}"

  - debug:
      var: output.splitlines()

  - debug:
      var: output

  - set_fact:
      lldp: "{{ output | regex_findall('^(\\S+)\\s+(Eth\\S+)\\s+\\d+\\s+\\S+\\s+(Ethernet\\S+)', multiline=True) }}"

  - debug:
      msg: "{{ lldp }}"
