---
- name: Generate arista configurations
  hosts: arista
  gather_facts: False

  tasks:
  - name: Generate Configurations from Jinja2 Template
    template:
      src: "./TEMPLATES/config.j2"
      dest: "./CFGS/{{ inventory_hostname }}_config.txt"
