---
- name: Week 7 - Ex2
  hosts: arista  
  gather_facts: False
  tasks:
    - block:
        - name: Configure DNS with incorrect password to fail the main block
          vars:
            ansible_ssh_pass: "wrongpassword"
          eos_config:
            lines:
              - "ip name-server {{ dns_server1 }}"
              - "ip name-server {{ dns_server2 }}"

      rescue: 
        - name: Configure DNS with correct password from environment variable
          vars:
            ansible_ssh_pass: "{{lookup('env','ANSIBLE_PASSWORD')}}"
          eos_config:
            lines:
              - "ip name-server {{ dns_server1 }}" 
              - "ip name-server {{ dns_server2 }}" 
