---
- name: Testing include_tasks
  hosts: localhost
  gather_facts: False
  vars:
    ip_addresses:
      - 10.1.1.1
      - 10.1.1.2
      - 10.1.1.3
      - 10.1.1.4


  tasks:
    - name: Include task
      include_tasks: include1.yml
      loop: "{{ ip_addresses }}"
