---
- name: Deploy ios, arista and nxos configurations via cli_config
  hosts: cisco:arista:nxos
  gather_facts: True

  tasks:
  - name: Global config
    set_fact:
      config: "{{ lookup('template', 'templates/{{ ansible_network_os }}/global.j2') }}"

  - name: View the generated configuration
    debug:
      var: config.splitlines()

  - name: Use cli_config module to deploy configuration from Jinja2 template
    cli_config:
      config: "{{ lookup('template', 'templates/{{ ansible_network_os }}/global.j2') }}"

- name: Deploy Junos configurations via cli_config
  hosts: juniper
  gather_facts: False
  vars:
    ansible_connection: network_cli

  tasks:
  - name: Use cli_config module to deploy configuration from Jinja2 template
    cli_config:
      config: "{{ lookup('template', 'templates/{{ ansible_network_os }}/global.j2') }}"
