---
- name: Deploy templated configuration via NAPALM
  hosts: arista5
  gather_facts: False

  tasks:
  - name: Generage configurations
    template:
      src: "templates/vlans.j2"
      dest: "config/{{ inventory_hostname}}.txt"

  - name: Deploy configuration via NAPALM
    napalm_install_config:
      replace_config: False
      commit_changes: False
      config_file: "config/{{ inventory_hostname}}.txt"
      diff_file: "diff/{{ inventory_hostname }}.txt"
